### ISSUE TITLE
Getting Problem when taking screenshot

### ISSUE THREAD

**Issue by nitinsinghthink** [voxeet/voxeet-sdk-android-gettingstarted#15] opened 2022-02-21 06:35 UTC
When i am trying to take screenshot/snapshot while connecting in room with enabled Video camera, I am only getting black screen 
![image](https://user-images.githubusercontent.com/81210488/154901511-8fa0cb79-5dd8-46c5-9ffd-1b056c78e35a.png)
.
Can anyone help me on this

**Comment by FabienLavocat** [comment] 2022-03-17 01:03
Duplicate of #16

**Closed as completed by FabienLavocat** 2022-03-17 01:03 UTC
